### ISSUE TITLE
The name

### ISSUE THREAD

**Issue by jeffreykegler** [latk/p5-MarpaX-Grammar-Preprocessor#3]
If the name is still in play, maybe it could be changed.  "Grammar::Preprocessor" is generic.  There may be others.

How about something like MarpaX::PPIF?  A kind of "trademark" name?

**Comment by latk** [comment]
@jeffreykegler Well, naming things *is* one of the hard problems in computer science.

There is one problem with the current name: it does not reflect that this module is specific to Marpa::R2's SLIF interface, so I would consider renaming to *MarpaX::Grammar::SlifPreprocessor* or *MarpaX::SLIF::Preprocessor* or so on. Would those be better? I doubt it, and unless I see a better alternative or strong argument for a specific name, I will not rename.

My thinking regarding Perl module names is that they should describe what the code does, not that they be easily recognizable. If a module is so large and important that it's a whole project of its own and has an ecosystem, then a recognizable, google-able, top-level name is more important. E.g. *Moo* and *Marpa* are good names because they are recognizable, as are *File::Temp*, *List::MoreUtils*, and *MarpaX::Grammar::Preprocessor* as these clearly describe what the module is about. I don't consider names like *Carp*, *Bread::Board*, or *MarpaX::PPIF* to be good names because they are misleading, not descriptive, or rely on cute metaphors. Outside of Perl, and especially looking towards Node.js and Ruby, I see far too many useless, clever names. Naming this module *MarpaX::PurpleDisturbance* or *MarpaX::Poikilogue* would do no one a favour.

A name being generic is not too big a problem: if someone thinks up another preprocessor with the distinctive feature being blue carrots, the module could be named *MarpaX::Grammar::BlueCarrotPreprocessor*. If there is no distinguishing feature, the module should not be released.

Notably, this module does not aspire to be a complete interface to Marpa, unlike the NAIF, SLIF, LUIF, or my previous IRIF experiment. Instead, it's just a preprocessor for SLIF grammars, and a pretty dumb one at that.

**Comment by jeffreykegler** [comment]
I take your point about generic names being a manageable problem.  When I started Marpa there was a Parse::Earley, a very limited module which has not been updated since 2002.  And it has not proved much of a problem.

**Comment by jeffreykegler** [comment]
Closing, for the reason in the preceding comment and per the consensus from the IRC discussion.
